import { TestResultCatCPCSchema } from '@dvsa/mes-test-schema/categories/CPC';

export const completedCPCTest: TestResultCatCPCSchema = {
  rekey: false,
  version: '3.25.4',
  category: 'CCPC',
  testData: {
    question1: {
      score: 10,
      title: 'Loading the vehicle',
      answer1: { label: 'Load to be placed up against the head board', selected: true },
      answer2: { label: 'Selects correct restraint item - load tensioning bar/webbing straps', selected: true },
      answer3: { label: 'Demonstrates competence in use of load tensioning bar/webbing straps', selected: false },
      answer4: { label: 'Demonstrates how to release the restraining device', selected: false },
      // eslint-disable-next-line max-len
      subtitle: 'You\'ve delivered part of your load and are left with half a load of empty roller cages inside your box van. Show me:',
      questionCode: 'Q14',
      // eslint-disable-next-line max-len
      additionalItems: ['a) by pointing to the correct distribution area(s) on this vehicle, where this load should be placed', 'b) which restraining device you\'d use to secure the load', 'c) how you\'d secure the load with the restraining device', 'd) how you\'d release the restraining device'],
    },
    question2: {
      score: 0,
      title: 'Security of vehicle and contents ',
      answer1: {
        // eslint-disable-next-line max-len
        label: 'Only park in secure, well lit vehicle parks. Where possible, park with the rear doors against a wall or backed up to another vehicle',
        selected: false,
      },
      answer2: { label: 'Remove keys and lock doors ', selected: false },
      answer3: { label: 'Activate or explain the use of any other security features', selected: false },
      answer4: { label: 'Walk around security check. For example, check the seals', selected: false },
      subtitle: 'You need to leave your vehicle.',
      questionCode: 'Q02',
      additionalItems: [
        'a) Where might you consider parking it?',
        'b) Explain what safety checks and security precautions you\'d take',
      ],
    },
    question3: {
      score: 0,
      title: 'Preventing criminality and trafficking in illegal immigrants',
      answer1: { label: 'Check external compartments', selected: false },
      answer2: { label: 'Check under and on top (visual, if possible) of the vehicle ', selected: false },
      answer3: {
        label: 'Check inside the cab and load security. For example, check the trailer seals and curtains',
        selected: false,
      },
      answer4: { label: 'Check fuel cap in place (not tampered with). Visual check', selected: false },
      // eslint-disable-next-line max-len
      subtitle: 'You\'ve had a comfort break just before boarding a cross channel ferry. Show me what checks you\'d make to this vehicle before driving through customs.',
      questionCode: 'Q07',
      additionalItems: [''],
    },
    question4: {
      score: 0,
      title: 'Assessing Emergency Situations',
      answer1: { label: 'Emptying the air tanks by pumping the footbrake', selected: false },
      answer2: {
        label: 'Restarting the engine and making sure the compressor recharges the system',
        selected: false,
      },
      answer3: { label: 'Stop the engine, apply footbrake and listen for leaks', selected: false },
      answer4: {
        label: 'Physical check of the air system to make sure air lines are serviceable',
        selected: false,
      },
      subtitle: 'You suspect a brake fault on this vehicle. Show me:',
      questionCode: 'Q09',
      additionalItems: [
        'a) what checks you can carry out to make sure the compressor is working properly ',
        'b) any checks you could make to identify air leaks',
      ],
    },
    question5: {
      score: 0,
      title: 'Ability to prevent physical risk',
      answer1: { label: 'Brakes', selected: false },
      answer2: { label: 'Horn', selected: false },
      answer3: { label: 'Exhaust system(s)', selected: false },
      answer4: { label: 'Lights/Reflectors', selected: false },
      answer5: { label: 'Mirrors', selected: false },
      answer6: { label: 'Instrument panel warning lights', selected: false },
      answer7: { label: 'Tyres / Wheel fixings ', selected: false },
      answer8: { label: 'Height marker', selected: false },
      answer9: { label: 'Wipers / Washers', selected: false },
      answer10: { label: 'Air leaks', selected: false },
      subtitle: 'Show me and explain the daily safety checks you\'d make to this vehicle before driving on the road.',
      questionCode: 'Q05',
      additionalItems: [],
    },
    combination: 'LGV5',
    totalPercent: 10,
  },
  journalData: {
    examiner: { staffNumber: '10000012', individualId: 1000012 },
    candidate: {
      prn: 9283749,
      gender: 'F',
      candidateId: 200,
      dateOfBirth: '1977-07-02',
      driverNumber: 'PEARS123456789DO',
      candidateName: { title: 'Miss', lastName: 'Aniston', firstName: 'Jennifer' },
      ethnicityCode: 'D',
      mobileTelephone: '07654 123456',
      candidateAddress: {
        postcode: 'PO57 0DE',
        addressLine1: 'Address Line 1',
        addressLine2: 'Address Line 2',
        addressLine3: 'Address Line 3',
        addressLine4: 'Address Line 4',
        addressLine5: 'Address Line 5',
      },
      previousADITests: 2,
      primaryTelephone: '01234 567890',
      secondaryTelephone: '04321 098765',
    },
    testCentre: { centreId: 54321, costCode: 'EXTC1', centreName: 'Example Test Centre' },
    testSlotAttributes: {
      start: '2020-07-06T08:00:00',
      slotId: 1185,
      slotType: 'Standard Test',
      welshTest: false,
      extendedTest: false,
      specialNeeds: false,
      vehicleTypeCode: 'C',
      entitlementCheck: false,
      examinerVisiting: false,
      specialNeedsCode: 'NONE',
      specialNeedsArray: ['None'],
      previousCancellation: ['Act of nature'],
    },
    applicationReference: { checkDigit: 1, applicationId: 11123466, bookingSequence: 1 },
  },
  rekeyReason: {
    other: { reason: '', selected: false },
    transfer: { selected: false },
    ipadIssue: { lost: false, broken: false, stolen: false, selected: false, technicalFault: false },
  },
  testSummary: { D255: false },
  activityCode: '2',
  changeMarker: false,
  accompaniment: { interpreter: true },
  examinerKeyed: 10000012,
  examinerBooked: 10000012,
  vehicleDetails: { configuration: 'Rigid', registrationNumber: 'F' },
  examinerConducted: 10000012,
  preTestDeclarations: {
    preTestSignature: 'some string',
    insuranceDeclarationAccepted: true,
    residencyDeclarationAccepted: true,
  },
  postTestDeclarations: {
    postTestSignature: '',
    healthDeclarationAccepted: false,
    passCertificateNumberReceived: false,
  },
  communicationPreferences: { updatedEmail: '', conductedLanguage: 'English', communicationMethod: 'Post' },
};
