export enum Competencies {
    controlsAccelerator = 'controlsAccelerator',
    controlsClutch = 'controlsClutch',
    controlsGears = 'controlsGears',
    controlsFootbrake = 'controlsFootbrake',
    controlsParkingBrake = 'controlsParkingBrake',
    controlsSteering = 'controlsSteering',
    precautions = 'precautions',
    ancillaryControls = 'ancillaryControls',
    moveOffSafety = 'moveOffSafety',
    moveOffControl = 'moveOffControl',
    useOfMirrorsSignalling = 'useOfMirrorsSignalling',
    useOfMirrorsChangeDirection = 'useOfMirrorsChangeDirection',
    useOfMirrorsChangeSpeed = 'useOfMirrorsChangeSpeed',
    signalsNecessary = 'signalsNecessary',
    signalsCorrectly = 'signalsCorrectly',
    signalsTimed = 'signalsTimed',
    junctionsApproachSpeed = 'junctionsApproachSpeed',
    junctionsObservation = 'junctionsObservation',
    junctionsTurningRight = 'junctionsTurningRight',
    junctionsTurningLeft = 'junctionsTurningLeft',
    junctionsCuttingCorners = 'junctionsCuttingCorners',
    judgementOvertaking = 'judgementOvertaking',
    judgementMeeting = 'judgementMeeting',
    judgementCrossing = 'judgementCrossing',
    positioningNormalDriving = 'positioningNormalDriving',
    positioningLaneDiscipline =  'positioningLaneDiscipline',
    clearance = 'clearance',
    followingDistance = 'followingDistance',
    useOfSpeed = 'useOfSpeed',
    progressAppropriateSpeed = 'progressAppropriateSpeed',
    progressUndueHesitation = 'progressUndueHesitation',
    responseToSignsTrafficSigns = 'responseToSignsTrafficSigns',
    responseToSignsRoadMarkings = 'responseToSignsRoadMarkings',
    responseToSignsTrafficLights = 'responseToSignsTrafficLights',
    responseToSignsTrafficControllers = 'responseToSignsTrafficControllers',
    responseToSignsOtherRoadUsers = 'responseToSignsOtherRoadUsers',
    pedestrianCrossings = 'pedestrianCrossings',
    positionNormalStops = 'positionNormalStops',
    awarenessPlanning = 'awarenessPlanning',
    vehicleChecks = 'vehicleChecks',
    reverseRightObservation = 'reverseRightObservation',
    reverseRightControl = 'reverseRightControl',
    reverseParkRoadObservation = 'reverseParkRoadObservation',
    reverseParkRoadControl = 'reverseParkRoadControl',
    reverseParkCarparkObservation = 'reverseParkCarparkObservation',
    reverseParkCarparkControl = 'reverseParkCarparkControl',
    forwardParkObservation = 'forwardParkObservation',
    forwardParkControl = 'forwardParkControl',
    controlledStop = 'controlledStop',
    eyesightTest = 'eyesightTest',
    uncoupleRecouple = 'uncoupleRecouple',
    reverseLeftControl = 'reverseLeftControl',
    reverseLeftObservation = 'reverseLeftObservation',

    useOfStand = 'useOfStand',
    manualHandling = 'manualHandling',
    slalom = 'slalom',
    slowControl = 'slowControl',
    uTurn = 'uTurn',

    avoidance = 'avoidance',
    emergencyStop = 'emergencyStop',

    avoidanceSpeedNotMet = 'avoidanceSpeedNotMet',
    emergencyStopSpeedNotMet = 'emergencyStopSpeedNotMet',
    positioningNormalRiding = 'positioningNormalRiding',
    clearanceOrObstructions = 'clearanceOrObstructions',
    safetyAndBalance = 'safetyAndBalance',
    controlsThrottle = 'controlsThrottle',

    controlsFrontBrake = 'controlsFrontBrake',
    controlsRearBrake = 'controlsRearBrake',
    controlsBalanceSlowControl = 'controlsBalanceSlowControl',
    bends = 'bends',

    highwayCodeSafety = 'highwayCodeSafety',
    safetyQuestions = 'safetyQuestions',
    pcvDoorExercise = 'pcvDoorExercise',

    rearObservationSignalling = 'rearObservationSignalling',
    rearObservationChangeDirection = 'rearObservationChangeDirection',
    rearObservationChangeSpeed = 'rearObservationChangeSpeed',
    positionNormalRiding = 'positionNormalRiding',
    judgementOvertakingFiltering = 'judgementOvertakingFiltering',
}

export enum englishCompetencyLabels {
    controlsAccelerator = 'Control - Accelerator',
    controlsClutch = 'Control - Clutch',
    controlsGears = 'Control - Gears',
    controlsFootbrake = 'Control - Footbrake',
    controlsParkingBrake = 'Control - Parking brake',
    controlsSteering = 'Control - Steering',
    precautions = 'Precautions',
    ancillaryControls = 'Control - Ancillary Controls',
    moveOffSafety = 'Move Away - Safety',
    moveOffControl = 'Move Away - Control',
    useOfMirrorsSignalling = 'Use of mirrors - Signalling',
    useOfMirrorsChangeDirection = 'Use of mirrors - Change direction',
    useOfMirrorsChangeSpeed = 'Use of mirrors - Change speed',
    signalsNecessary = 'Signals - Necessary',
    signalsCorrectly = 'Signals - Correctly',
    signalsTimed = 'Signals - Timed',
    junctionsApproachSpeed = 'Junctions - Approach speed',
    junctionsObservation = 'Junctions - Observation',
    junctionsTurningRight = 'Junctions - Turning right',
    junctionsTurningLeft = 'Junctions - Turning left',
    junctionsCuttingCorners = 'Junctions - Cutting corners',
    judgementOvertaking = 'Judgement - Overtaking',
    judgementMeeting = 'Judgement - Meeting',
    judgementCrossing = 'Judgement - Crossing',
    positioningNormalDriving = 'Positioning - Normal driving',
    positioningLaneDiscipline = 'Positioning - Lane discipline',
    clearance = 'Clearance',
    followingDistance = 'Following distance',
    useOfSpeed = 'Use of speed',
    progressAppropriateSpeed = 'Progress - Appropriate speed',
    progressUndueHesitation = 'Progress - Undue hesitation',
    responseToSignsTrafficSigns = 'Response to signs / signals - Traffic signs',
    responseToSignsRoadMarkings = 'Response to signs / signals - Road markings',
    responseToSignsTrafficLights = 'Response to signs / signals - Traffic lights',
    responseToSignsTrafficControllers = 'Response to signs / signals - Traffic controllers',
    responseToSignsOtherRoadUsers = 'Response to signs / signals - Other road users',
    pedestrianCrossings = 'Pedestrian crossings',
    positionNormalStops = 'Position/normal stop',
    awarenessPlanning = 'Awareness / Planning',
    outcomeControlledStop = 'Controlled stop',
    reverseRightObservation = 'Reverse right - Observation',
    reverseRightControl = 'Reverse right - Control',
    reverseParkRoadObservation = 'Reverse park (road) - Observation',
    reverseParkRoadControl = 'Reverse park (road) - Control',
    reverseParkCarparkObservation = 'Reverse park (car park) - Observation',
    reverseParkCarparkControl = 'Reverse park (car park) - Control',
    forwardParkObservation = 'Forward park - Observation',
    forwardParkControl = 'Forward park - Control',
    controlledStop = 'Controlled Stop',
    vehicleChecks = 'Vehicle checks',
    eyesightTest = 'Eyesight test',
    reverseLeftControl = 'Reverse - Control',
    reverseLeftObservation = 'Reverse - Observation',
    uncoupleRecouple = 'Uncouple / Recouple',

    useOfStand = 'Use of stand',
    manualHandling = 'Manual handling',
    slalom = 'Slalom / Figure 8',
    slowControl = 'Slow control',
    uTurn = 'U Turn Exercise',

    avoidance = 'Avoidance Ex. Control Stop',
    emergencyStop = 'Emergency stop',

    avoidanceSpeedNotMet = 'Avoidance Ex. Control Stop - Speed requirement not met',
    emergencyStopSpeedNotMet = 'Emergency Stop - Speed requirement not met',
    positioningNormalRiding = 'Positioning - Normal riding',
    clearanceOrObstructions = 'Clearance / Obstructions',
    safetyAndBalance = 'Safety and balance questions',
    controlsThrottle = 'Control - Throttle',

    controlsFrontBrake = 'Control - Front brake',
    controlsRearBrake = 'Control - Rear brake',
    controlsBalanceSlowControl = 'Control - Balance / Slow control',
    bends = 'Bends',

    highwayCodeSafety = 'H/Code / Safety',
    safetyQuestions = 'Safety Questions',
    pcvDoorExercise = 'PCV Door exercise',

    rearObservationSignalling = 'Rear Observation - Signalling',
    rearObservationChangeDirection = 'Rear Observation - Change Direction',
    rearObservationChangeSpeed = 'Rear Observation - Change Speed',
    positionNormalRiding = 'Positioning - Normal Riding',
    judgementOvertakingFiltering = 'Judgement - Overtaking / Filtering',

}

export enum welshCompetencyLabels {
  controlsAccelerator = 'Rheolaeth - sbardun',
  controlsClutch = 'Rheolaeth - cydiwr',
  controlsGears = 'Rheolaeth - gêr',
  controlsFootbrake = 'Rheolaeth - brêc troed',
  controlsParkingBrake = 'Rheolaeth - brêc parcio',
  controlsSteering = 'Rheolaeth - y llyw',
  precautions = 'Rhagofalon',
  ancillaryControls = 'Rheolyddion atodol',
  moveOffSafety = 'Symud i ffwrdd - diogelwch',
  moveOffControl = 'Symud i ffwrdd - dan reolaeth',
  useOfMirrorsSignalling = 'Defnyddio drychau - rhoi signalau',
  useOfMirrorsChangeDirection = 'Defnyddio drychau - newid cyfeiriad',
  useOfMirrorsChangeSpeed = 'Defnyddio drychau - newid cyflymder',
  signalsNecessary = 'Signalau - angenrheidiol',
  signalsCorrectly = 'Signalau - yn gywir',
  signalsTimed = 'Signalau - amseru',
  junctionsApproachSpeed = 'Cyffyrdd - cyflymder agosáu',
  junctionsObservation = 'Cyffyrdd - gwyliadwriaeth',
  junctionsTurningRight = 'Cyffyrdd - troi i’r dde',
  junctionsTurningLeft = 'Cyffyrdd - troi i’r chwith',
  junctionsCuttingCorners = 'Cyffyrdd - torri corneli',
  judgementOvertaking = 'Doethineb - goddiweddyd',
  judgementMeeting = 'Doethineb - dod i gyfarfod cerbydau',
  judgementCrossing = 'Doethineb - croesi',
  positioningNormalDriving = 'Lleoli ar y ffordd - gyrru arferol',
  positioningLaneDiscipline = 'Lleoli ar y ffordd - disgyblaeth lôn',
  clearance = 'Clirio',
  followingDistance = 'Pellter dilyn',
  useOfSpeed = 'Defnyddio cyflymder',
  progressAppropriateSpeed = 'Symud ymlaen - cyflymder addas',
  progressUndueHesitation = 'Symud ymlaen - petruso gormodol',
  responseToSignsTrafficSigns = 'Ymateb I arwyddion ffyrdd / signalau - arwyddion traffig',
  responseToSignsRoadMarkings = 'Ymateb I arwyddion ffyrdd / signalau - marciau ar y ffordd',
  responseToSignsTrafficLights = 'Ymateb I arwyddion ffyrdd / signalau - goleuadau traffig',
  responseToSignsTrafficControllers = 'Ymateb I arwyddion ffyrdd / signalau - rheolwyr traffig',
  responseToSignsOtherRoadUsers = 'Ymateb I arwyddion ffyrdd / signalau - defnyddwyr ffordd eraill',
  pedestrianCrossings = 'Croesfannau cerddwyr',
  positionNormalStops = 'Lleoli / stopio arferol',
  awarenessPlanning = 'Ymwybyddiaeth / cynllunio',
  outcomeControlledStop = 'Stopio dan Reolaeth',
  reverseRightObservation = 'Bacio i’r dde - gwyliadwriaeth',
  reverseRightControl = 'Bacio i’r dde - dan reolaeth',
  reverseParkRoadObservation = 'Parcio wrth wrthdroi (Ar y ffordd) - gwyliadwriaeth',
  reverseParkRoadControl = 'Parcio wrth wrthdroi (Ar y ffordd) - dan reolaeth',
  reverseParkCarparkObservation = 'Parcio wrth wrthdroi (Maes parcio) - gwyliadwriaeth',
  reverseParkCarparkControl = 'Parcio wrth wrthdroi (Maes parcio) - dan reolaeth',
  forwardParkObservation = 'Parcio Ymlaen - gwyliadwriaeth',
  forwardParkControl = 'Parcio Ymlaen - dan reolaeth',
  controlledStop = 'Stopio dan Reolaeth',
  vehicleChecks = 'Gwirio’r cerbyd',
  eyesightTest = 'Prawf Golwg',
  uncoupleRecouple = 'Dadfachu / Ailfachu',
  reverseLeftObservation = 'Gwrthdroi - gwyliadwriaeth',
  reverseLeftControl = 'Gwrthdroi - dan reolaeth',

  useOfStand = 'Defnyddio stondin',
  manualHandling = 'Codi a chario',
  slalom = 'Slalom / Ffigwr 8',
  slowControl = 'Rheolydd araf',
  uTurn = 'Ymarfer tro \'U\'',

  avoidance = 'Ymarfer osgoi/stop dan reolaeth',
  emergencyStop = 'Stop brys',

  avoidanceSpeedNotMet = 'Ymarfer osgoi/stop dan reolaeth - Gofyniad Cyflymder heb ei fodloni',
  emergencyStopSpeedNotMet = 'Stop brys - Gofyniad Cyflymder heb ei fodloni',
  positioningNormalRiding = 'Lleoli ar y ffordd - Beicio arferol',
  clearanceOrObstructions = 'Clirio / Rhwystrau',
  controlsThrottle = 'Rheolaeth - Throtl',

  controlsFrontBrake = 'Rheolaeth - Brêc blaen',
  controlsRearBrake = 'Rheolaeth - Brêc ôl',
  controlsBalanceSlowControl = 'Rheolaeth - Cydbwysedd / Rheolaeth araf',
  bends = 'Troeon',

  highwayCodeSafety = '[CY] H/Code / Safety',
  safetyQuestions = 'Cwestiynau diogelwch',
  pcvDoorExercise = 'Ymarfer Drws PCV',

  rearObservationSignalling = 'Ôl Arsylwi - Signalau',
  rearObservationChangeDirection = 'Ôl Arsylwi - Newid Cyfeiriad',
  rearObservationChangeSpeed = 'Ôl Arsylwi - Newid Cyflymder',
  positionNormalRiding = 'Lleoli - Marchogaeth Normal',
  judgementOvertakingFiltering = 'Barnu Goddiweddyd /Hidlo',

}

export enum englishTexts {
  abortedAttempt = 'Aborted attempt',
}

export enum welshTexts {
  abortedAttempt = 'Ymgais wedi’I hatal',
}
