import * as markdownIt from 'markdown-it';
import * as pdf from 'html-pdf';

import { getRenderedText } from "../../src/functions/sendCandidateResults/application/service/send-notification";
import { TestOutcome } from "../../src/functions/sendCandidateResults/domain/test-outcome";
import { Language } from "../../src/functions/sendCandidateResults/domain/conducted-language";
import {
  personalisationCatADI2Pass,
  personalisationCatADI2Fail,
  personalisationCatADI3Pass,
  personalisationCatADI3Fail,
} from "../../src/functions/sendCandidateResults/application/service/__mocks__/personalisation-details";

const templates = [];

//Add templates to generate pdfs
templates.push(
  //ADI2
  {
    filename: 'adi2PassEnglish',
    markdown: getRenderedText(TestOutcome.PASS, personalisationCatADI2Pass, Language.ENGLISH, false)
  },
  {
    filename: 'adi2FailEnglish',
    markdown: getRenderedText(TestOutcome.FAIL, personalisationCatADI2Fail, Language.ENGLISH, false)
  },
  //ADI3
  {
    filename: 'adi3PassEnglish',
    markdown: getRenderedText(TestOutcome.PASS, personalisationCatADI3Pass, Language.ENGLISH, false)
  },
  {
    filename: 'adi3FailEnglishFirstOrSecond',
    markdown: getRenderedText(TestOutcome.FAIL, personalisationCatADI3Fail, Language.ENGLISH, false)
  },
  {
    filename: 'adi3FailEnglishThird',
    markdown: getRenderedText(TestOutcome.FAIL, personalisationCatADI3Fail, Language.ENGLISH, false)
  },
  // Vocational
  {
    filename: 'vocational4PassEnglish',
    markdown: getRenderedText(TestOutcome.FAIL, personalisationCatADI3Fail, Language.ENGLISH, false)
  },
);


templates.forEach((template: { filename: string; markdown: string | undefined; }) => {
    generatePdf(template.filename, template.markdown)
  }
)

/**
 * Take filenames, and the markdown generated by the renderText function and generate a pdf for evaluation
 * @param filename
 * @param template
 */
function generatePdf(filename: string, template: string | undefined) {
  const md = markdownIt();
  const htmlContent = md.render(template as string);
  const outputFilePath = `integration/output/${filename}.pdf`;
  pdf.create(htmlContent).toFile(outputFilePath, (err: any, res: any) => {
    if (err) return console.log(err);
    console.log(res);
  });
}
