import { PersonalisationDetails } from '../../../domain/personalisation.model';
import { TestCategory } from '@dvsa/mes-test-schema/category-definitions/common/test-category';

const commonCandidateDetails = {
  applicationReference: 12345678901,
  date: '25 December 2024',
  candidateName: 'Miss driving candidate',
  location: 'Example Test Centre',
  address_line_1: 'Mock Address 1',
  address_line_2: 'Mock Address 2',
  address_line_3: 'Mock Address 3',
  address_line_4: 'Mock Address 4',
  address_line_5: 'Mock Address 5',
  address_line_6: 'Mock Address 6',
  postcode: 'PO10 0AB',
  communicationMethod: 'EMAIL',
};

export const personalisationCatADI2Fail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI2,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: [ 'Signals - Correctly' ],
  showSeriousFaults: true,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatADIFail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI2,
  drivingFaults: [
    'Vehicle checks, 2',
    'Pedestrian crossings, 1',
    'Use of mirrors - Signalling, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Use of mirrors - Change direction' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatADIFail3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI2,
  drivingFaults: [
    'Vehicle checks, 2',
    'Pedestrian crossings, 1',
    'Use of mirrors - Signalling, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Signals - Correctly' ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Use of mirrors - Change direction' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatADI2Pass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI2,
  drivingFaults: [ 'Control - Accelerator, 4', 'Vehicle checks, 3' ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatADI2Pass2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI2,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatADI3FailFirstOrSecond: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI3,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: true,
  code4: true,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'lesson theme for test' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'feedback details',
  positionType: 'in',
  previousAttempts: 1,
  prn: '1105322',
};

export const personalisationCatADI3FailFirstOrSecond2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI3,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'another theme' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'feedback details',
  positionType: 'in',
  previousAttempts: 1,
  prn: '1105322',
};

export const personalisationCatADI3FailThird: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI3,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: true,
  code4: true,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'lesson theme 2', 'Motorways' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'feedback goes here',
  positionType: 'in',
  previousAttempts: 2,
  prn: '1105322',
};

export const personalisationCatADI3FailThird2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI3,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'lesson theme 2', 'Motorways' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'feedback goes here',
  positionType: 'in',
  previousAttempts: 2,
  prn: '1105322',
};

export const personalisationCatADI3Pass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.ADI3,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '12',
  lp1Score: '3',
  lp2Score: '3',
  lp3Score: '3',
  lp4Score: '3',
  riskManagementScore: '15',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '3',
  teachingLearningStrategiesScore: '24',
  tls1Score: '3',
  tls2Score: '3',
  tls3Score: '3',
  tls4Score: '3',
  tls5Score: '3',
  tls6Score: '3',
  tls7Score: '3',
  tls8Score: '3',
  totalScore: '51',
  studentLevel: 'Trained',
  lessonThemes: [ 'Junctions', 'Motorways' ],
  grade: 'A',
  showGrade: false,
  result: 'were successful',
  feedback: 'M',
  positionType: 'in',
  prn: '4405399',
};

export const personalisationCatSCFailFirstOrSecond: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.SC,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
  isADI3: false,
  isSC: true,
  RMFail: true,
  code4: true,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '5',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '2',
  lp4Score: '1',
  riskManagementScore: '5',
  rm1Score: '1',
  rm2Score: '1',
  rm3Score: '2',
  rm4Score: '1',
  rm5Score: '0',
  teachingLearningStrategiesScore: '9',
  tls1Score: '1',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '2',
  tls5Score: '1',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '2',
  totalScore: '19',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'failed',
  feedback: 'Saul goodman',
  positionType: 'on',
  previousAttempts: 1,
  prn: '3322408',
};

export const personalisationCatSCFailFirstOrSecond2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.SC,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '5',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '2',
  lp4Score: '1',
  riskManagementScore: '5',
  rm1Score: '1',
  rm2Score: '1',
  rm3Score: '2',
  rm4Score: '1',
  rm5Score: '0',
  teachingLearningStrategiesScore: '9',
  tls1Score: '1',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '2',
  tls5Score: '1',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '2',
  totalScore: '19',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'failed',
  feedback: 'Saul goodman',
  positionType: 'on',
  previousAttempts: 1,
  prn: '3322408',
};

export const personalisationCatSCFailThird: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.SC,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: false,
  isSC: true,
  RMFail: true,
  code4: true,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '5',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '2',
  lp4Score: '1',
  riskManagementScore: '5',
  rm1Score: '1',
  rm2Score: '1',
  rm3Score: '2',
  rm4Score: '1',
  rm5Score: '0',
  teachingLearningStrategiesScore: '9',
  tls1Score: '1',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '2',
  tls5Score: '1',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '2',
  totalScore: '19',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'failed',
  feedback: 'Saul goodman',
  positionType: 'on',
  previousAttempts: 2,
  prn: '3322408',
};

export const personalisationCatSCFailThird2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.SC,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '5',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '2',
  lp4Score: '1',
  riskManagementScore: '5',
  rm1Score: '1',
  rm2Score: '1',
  rm3Score: '2',
  rm4Score: '1',
  rm5Score: '0',
  teachingLearningStrategiesScore: '9',
  tls1Score: '1',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '2',
  tls5Score: '1',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '2',
  totalScore: '19',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'failed',
  feedback: 'Saul goodman',
  positionType: 'on',
  previousAttempts: 2,
  prn: '3322408',
};

export const personalisationCatSCPass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.SC,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: false,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '10',
  lp1Score: '3',
  lp2Score: '2',
  lp3Score: '3',
  lp4Score: '2',
  riskManagementScore: '15',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '3',
  teachingLearningStrategiesScore: '22',
  tls1Score: '3',
  tls2Score: '3',
  tls3Score: '3',
  tls4Score: '3',
  tls5Score: '2',
  tls6Score: '3',
  tls7Score: '3',
  tls8Score: '2',
  totalScore: '47',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving', 'Junctions' ],
  grade: 'B',
  showGrade: true,
  result: 'passed',
  feedback: 'Saul goodman',
  positionType: 'on',
  prn: '3322408',
};

export const personalisationCatBFail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.B,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationCatBFail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.B,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
    'Junctions - Turning right, 1',
    'Junctions - Approach speed, 1',
    'Junctions - Cutting corners, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Junctions - Observation' ],
  showSeriousFaults: true,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationCatBFail3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.B,
  drivingFaults: [
    'Judgement - Meeting, 2',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 5',
    'Junctions - Turning left, 3',
    'Junctions - Turning right, 7',
    'Junctions - Approach speed, 4',
    'Junctions - Cutting corners, 6',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationCatBPass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.B,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: true,
  showSeriousFaults: false,
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationCatBPass2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.B,
  drivingFaults: '',
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: false,
  showSeriousFaults: false,
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatAMod1Fail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM1,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  result: 'were unsuccessful',
  showEmergencyFirstAttempt: true,
  showEmergencySecondAttempt: false,
  emergencyFirstAttempt: '55',
  emergencySecondAttempt: '78',
  showAvoidanceFirstAttempt: true,
  showAvoidanceSecondAttempt: false,
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '32',
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationCatAMod1Fail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM1,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
    'Junctions - Turning right, 1',
    'Junctions - Approach speed, 1',
    'Junctions - Cutting corners, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Junctions - Observation' ],
  showSeriousFaults: true,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  result: 'were unsuccessful',
  showEmergencyFirstAttempt: true,
  showEmergencySecondAttempt: true,
  emergencyFirstAttempt: '55',
  emergencySecondAttempt: '78',
  showAvoidanceFirstAttempt: true,
  showAvoidanceSecondAttempt: false,
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '32',
};

export const personalisationCatAMod1Fail3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM1,
  drivingFaults: [
    'Judgement - Meeting, 2',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 5',
    'Junctions - Turning left, 3',
    'Junctions - Turning right, 7',
    'Junctions - Approach speed, 4',
    'Junctions - Cutting corners, 6',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  result: 'were unsuccessful',
  showEmergencyFirstAttempt: false,
  showEmergencySecondAttempt: false,
  emergencyFirstAttempt: '55',
  emergencySecondAttempt: '78',
  showAvoidanceFirstAttempt: false,
  showAvoidanceSecondAttempt: false,
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '32',
};

export const personalisationCatAMod1Pass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM1,
  drivingFaults: [ 'Move away - Safety, 1' ],
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: true,
  showSeriousFaults: false,
  showDangerousFaults: false,
  result: 'were successful',
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '2',
  showEcoText: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatAMod1Pass2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM1,
  drivingFaults: '',
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: false,
  showSeriousFaults: false,
  showDangerousFaults: false,
  result: 'were successful',
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '2',
  showEcoText: false,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatAMod1Pass3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM1,
  drivingFaults: '',
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: false,
  showSeriousFaults: false,
  showDangerousFaults: false,
  result: 'were successful',
  showEmergencyFirstAttempt: false,
  showEmergencySecondAttempt: false,
  emergencyFirstAttempt: '55',
  emergencySecondAttempt: '78',
  showAvoidanceFirstAttempt: false,
  showAvoidanceSecondAttempt: false,
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '32',
  showEcoText: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod2Fail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM2,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  result: 'were unsuccessful',
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod2Fail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM2,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
    'Junctions - Turning right, 1',
    'Junctions - Approach speed, 1',
    'Junctions - Cutting corners, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Junctions - Observation' ],
  showSeriousFaults: true,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod2Fail3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM2,
  drivingFaults: [
    'Judgement - Meeting, 2',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 5',
    'Junctions - Turning left, 3',
    'Junctions - Turning right, 7',
    'Junctions - Approach speed, 4',
    'Junctions - Cutting corners, 6',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  result: 'were unsuccessful',
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod2Pass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUA1M2,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: true,
  showSeriousFaults: false,
  showDangerousFaults: false,
  result: 'were successful',
  showEcoText: true,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationCatMod2Pass2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.EUAM2,
  drivingFaults: '',
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: false,
  showSeriousFaults: false,
  showDangerousFaults: false,
  result: 'were successful',
  showEcoText: false,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationSpecialistVehicleFail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.F,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationSpecialistVehicleFail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.F,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};


export const personalisationSpecialistVehicleFail3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.F,
  drivingFaults: [
    'Judgement - Meeting, 2',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 5',
    'Junctions - Turning left, 3',
    'Junctions - Turning right, 7',
    'Junctions - Approach speed, 4',
    'Junctions - Cutting corners, 6',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};


export const personalisationSpecialistVehiclePass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.F,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: true,
  showSeriousFaults: false,
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationSpecialistVehiclePass2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.B,
  drivingFaults: '',
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: false,
  showSeriousFaults: false,
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationVocational3aFail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.CEM,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationVocational3aFail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.CEM,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: [ 'Junctions - Observation' ],
  showSeriousFaults: true,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationVocational3aPass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.C1M,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationVocational3bFail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.C,
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationVocational3bFail2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.C,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
    'Junctions - Turning right, 1',
    'Junctions - Approach speed, 1',
    'Junctions - Cutting corners, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Junctions - Observation' ],
  showSeriousFaults: true,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationVocational3bFail3: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.C,
  drivingFaults: [
    'Judgement - Meeting, 2',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 5',
    'Junctions - Turning left, 3',
    'Junctions - Turning right, 7',
    'Junctions - Approach speed, 4',
    'Junctions - Cutting corners, 6',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
};

export const personalisationVocational3bPass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.C,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: true,
  showSeriousFaults: false,
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  showLGVText: false,
};

export const personalisationVocational3bPass2: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.C,
  drivingFaults: '',
  seriousFaults: '',
  dangerousFaults: '',
  showDrivingFaults: false,
  showSeriousFaults: false,
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaPhysical: false,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  showLGVText: true,
};

export const personalisationVocational4Fail: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.CCPC,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: false,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score: '1',
  q2Score: '2',
  q3Score: '3',
  q4Score: '3',
  q5Score: '3',
  totalScore: '12',
};

export const personalisationVocational4Pass: PersonalisationDetails = {
  ...commonCandidateDetails,
  category: TestCategory.CCPC,
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: false,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score: '15',
  q2Score: '18',
  q3Score: '17',
  q4Score: '15',
  q5Score: '12',
  totalScore: '77',
};
