import { PersonalisationDetails } from '../../../domain/personalisation.model';
import { TestCategory } from '@dvsa/mes-test-schema/category-definitions/common/test-category';

export const personalisationVocational4Pass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345678,
  category: TestCategory.CCPC,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre for CPC Part 4',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score:'15',
  q2Score:'18',
  q3Score:'17',
  q4Score:'15',
  q5Score:'12',
  totalScore: '77',
};

export const personalisationVocational4Fail: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345678,
  category: TestCategory.CCPC,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'CPC Fail Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score:'1',
  q2Score:'2',
  q3Score:'3',
  q4Score:'3',
  q5Score:'3',
  totalScore: '12',
};

export const personalisationVocational3aPass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345638,
  category: TestCategory.C1M,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre for 3a Manoeuvres',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score:'1',
  q2Score:'2',
  q3Score:'3',
  q4Score:'4',
  q5Score:'5',
  totalScore: '21',
};

export const personalisationVocational3aFail: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345638,
  category: TestCategory.CEM,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score:'1',
  q2Score:'2',
  q3Score:'3',
  q4Score:'3',
  q5Score:'3',
  totalScore: '11',
};

export const personalisationVocational3bPass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345658,
  category: TestCategory.C,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre for 3b Vocational',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score:'1',
  q2Score:'2',
  q3Score:'3',
  q4Score:'4',
  q5Score:'5',
  totalScore: '21',
};

export const personalisationVocational3bFail: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345638,
  category: TestCategory.C,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  q1Score:'1',
  q2Score:'2',
  q3Score:'3',
  q4Score:'3',
  q5Score:'3',
  totalScore: '11',
};

export const personalisationCatBPass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345678,
  category: TestCategory.B,
  date: '01 January 1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: false,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod1Pass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345698,
  category: TestCategory.EUAM1,
  date: '01/01/1990',
  drivingFaults: [ 'Move away - Safety, 1' ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  result: 'were successful',
  avoidanceFirstAttempt: '3',
  avoidanceSecondAttempt: '2',
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod1Fail: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345698,
  category: TestCategory.EUAM1,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  result: 'were unsuccessful',
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod2Pass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345678,
  category: TestCategory.EUAM2,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: false,
  result: 'were successful',
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatMod2Fail: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345678,
  category: TestCategory.EUAM2,
  date: '01/01/1990',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
  ],
  seriousFaults: [ 'Signals - Necessary' ],
  dangerousFaults: [ 'Junctions - Observation' ],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  result: 'were unsuccessful',
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personalisationCatBFail: PersonalisationDetails = {
  applicationReference: 14091418816,
  category: TestCategory.B,
  date: '14 December 2023',
  location: 'Graham\'s Centre',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
    'Junctions - Turning right, 1',
    'Junctions - Approach speed, 1',
    'Junctions - Cutting corners, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: false,
  showEtaPhysical: true,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Miss Richard Fisher',
  address_line_1: 'Mock Address 1',
  address_line_2: 'Mock Address 2',
  address_line_3: 'Mock Address 3',
  address_line_4: '16 King St',
  address_line_5: undefined,
  address_line_6: 'Nottingham',
  postcode: 'NG1 2AS',
};

export const personalisationCatADI2Pass: PersonalisationDetails = {
  applicationReference: 22123400011,
  category: TestCategory.ADI2,
  date: '13 December 2023',
  location: 'ADI2 Pass Test Centre',
  drivingFaults: [ 'Control - Accelerator, 4', 'Vehicle checks, 3' ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'miss Anna Firstlis',
  address_line_1: 'miss Anna Firstlis',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: 'Address Line 3',
  address_line_5: 'Address Line 4',
  address_line_6: 'Address Line 5',
  postcode: 'PO57 0DE',
};

export const personalisationCatADI2Fail: PersonalisationDetails = {
  applicationReference: 22123903031,
  category: TestCategory.ADI2,
  date: '27 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [
    'Vehicle checks, 2',
    'Pedestrian crossings, 1',
    'Use of mirrors - Signalling, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Signals - Correctly' ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Use of mirrors - Change direction' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Mr Polo Shirt',
  address_line_1: 'Mr Polo Shirt',
  address_line_2: '4567 Station Street',
  address_line_3: 'Someplace',
  address_line_4: 'Sometown',
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'AB12 3CD',
};

export const personalisationCatADI3Pass: PersonalisationDetails = {
  applicationReference: 23123428013,
  category: TestCategory.ADI3,
  date: '14 December 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '12',
  lp1Score: '3',
  lp2Score: '3',
  lp3Score: '3',
  lp4Score: '3',
  riskManagementScore: '15',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '3',
  teachingLearningStrategiesScore: '24',
  tls1Score: '3',
  tls2Score: '3',
  tls3Score: '3',
  tls4Score: '3',
  tls5Score: '3',
  tls6Score: '3',
  tls7Score: '3',
  tls8Score: '3',
  totalScore: '51',
  studentLevel: 'Trained',
  lessonThemes: [ 'Junctions', 'Motorways' ],
  grade: 'A',
  showGrade: false,
  result: 'were successful',
  feedback: 'M',
  positionType: 'in',
  prn: '4405399',
  candidateName: 'Mr Mike Wheeler',
  address_line_1: 'Mr Mike Wheeler',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personalisationCatADI3FailFirstOrSecond: PersonalisationDetails = {
  applicationReference: 23123427011,
  category: TestCategory.ADI3,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'Ssdfghdfgdfgd' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'Review feedback',
  positionType: 'in',
  previousAttempts: 1,
  prn: '1105322',
  candidateName: 'Mr Will Byers',
  address_line_1: 'Mr Will Byers',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personalisationCatADI3FailThird: PersonalisationDetails = {
  applicationReference: 23123427011,
  category: TestCategory.ADI3,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'Ssdfghdfgdfgd' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'Review feedback',
  positionType: 'in',
  previousAttempts: 2,
  prn: '1105322',
  candidateName: 'Mr Will Byers',
  address_line_1: 'Mr Will Byers',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personalisationCatSCPass: PersonalisationDetails = {
  applicationReference: 23150009011,
  category: TestCategory.SC,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '10',
  lp1Score: '3',
  lp2Score: '2',
  lp3Score: '3',
  lp4Score: '2',
  riskManagementScore: '15',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '3',
  teachingLearningStrategiesScore: '22',
  tls1Score: '3',
  tls2Score: '3',
  tls3Score: '3',
  tls4Score: '3',
  tls5Score: '2',
  tls6Score: '3',
  tls7Score: '3',
  tls8Score: '2',
  totalScore: '47',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving', 'Junctions' ],
  grade: 'B',
  showGrade: true,
  result: 'passed',
  feedback: 'Saul goodman',
  positionType: 'on',
  prn: '3322408',
  candidateName: 'Mr Stan Lee',
  address_line_1: 'Mr Stan Lee',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personalisationTractorPass: PersonalisationDetails = {
  applicationReference: 23150009011,
  category: TestCategory.F,
  date: '30 November 2023',
  location: 'Isolated test centre for Tractor',
  candidateName: 'Dai Tractor',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  result: 'pass',
};

export const personalisationTractorFail: PersonalisationDetails = {
  applicationReference: 23150009012,
  category: TestCategory.F,
  date: '30 November 2023',
  location: 'Isolated test centre for Tractor',
  candidateName: 'Dai Tractor',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  result: 'fail',
};

export const personalisationCatSCFailFirstOrSecond: PersonalisationDetails = {
  applicationReference: 23150009011,
  category: TestCategory.SC,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '5',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '2',
  lp4Score: '1',
  riskManagementScore: '5',
  rm1Score: '1',
  rm2Score: '1',
  rm3Score: '2',
  rm4Score: '1',
  rm5Score: '0',
  teachingLearningStrategiesScore: '9',
  tls1Score: '1',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '2',
  tls5Score: '1',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '2',
  totalScore: '19',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'failed',
  feedback: 'Saul goodman',
  positionType: 'on',
  previousAttempts: 1,
  prn: '3322408',
  candidateName: 'Mr Stangus Lee',
  address_line_1: 'Mr Stangus Lee',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personalisationCatSCFailThird: PersonalisationDetails = {
  applicationReference: 23150009011,
  category: TestCategory.SC,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '5',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '2',
  lp4Score: '1',
  riskManagementScore: '5',
  rm1Score: '1',
  rm2Score: '1',
  rm3Score: '2',
  rm4Score: '1',
  rm5Score: '0',
  teachingLearningStrategiesScore: '9',
  tls1Score: '1',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '2',
  tls5Score: '1',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '2',
  totalScore: '19',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'failed',
  feedback: 'Saul goodman',
  positionType: 'on',
  previousAttempts: 2,
  prn: '3322408',
  candidateName: 'Mr Stangus Lee',
  address_line_1: 'Mr Stangus Lee',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};
