import { PersonalisationDetails } from '../../../domain/personalisation.model';
import { TestCategory } from '@dvsa/mes-test-schema/category-definitions/common/test-category';

export const personlisationCatBPass: PersonalisationDetails = {
  candidateName: 'some name',
  address_line_1: 'add1',
  address_line_2: 'add2',
  postcode: 'sa1',
  applicationReference: 12345678,
  category: TestCategory.B,
  date: '01/01/1990',
  drivingFaults: [],
  seriousFaults: [],
  dangerousFaults: [],
  location: 'Test Centre',
  showDangerousFaults: true,
  showDrivingFaults: true,
  showEcoText: true,
  showSeriousFaults: true,
  showEtaText: true,
  showEtaPhysical: true,
  showEtaVerbal: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
};

export const personlisationCatBFail: PersonalisationDetails = {
  applicationReference: 14091418816,
  category: TestCategory.B,
  date: '14 December 2023',
  location: 'Graham\'s Centre',
  drivingFaults: [
    'Judgement - Meeting, 1',
    'Judgement - Overtaking, 1',
    'Junctions - Observation, 1',
    'Junctions - Turning left, 1',
    'Junctions - Turning right, 1',
    'Junctions - Approach speed, 1',
    'Junctions - Cutting corners, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Miss Dick Fisher',
  address_line_1: 'Miss Dick Fisher',
  address_line_2: 'c/o Matthew Bellamy (Kainos)',
  address_line_3: 'BJSS, Fothergill House',
  address_line_4: '16 King St',
  address_line_5: undefined,
  address_line_6: 'Nottingham',
  postcode: 'NG1 2AS',
};

export const personlisationCatCPass: PersonalisationDetails = {
  applicationReference: 72345622011,
  category: TestCategory.C,
  date: '27 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [
    'Vehicle checks, 2',
    'Control - Gears, 1',
    'Use of mirrors - Change direction, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  candidateName: 'Ms Shirley Benton',
  address_line_1: 'Ms Shirley Benton',
  address_line_2: '57 Furman Street',
  address_line_3: 'Rapelye Street',
  address_line_4: 'Halsey Street',
  address_line_5: 'Dale',
  address_line_6: 'Address Line 5',
  postcode: 'BR82 0DE',
};

export const personlisationCatCFail: PersonalisationDetails = {
  applicationReference: 72345633011,
  category: TestCategory.C,
  date: '27 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [ 'Vehicle checks, 4', 'Use of mirrors - Signalling, 1' ],
  showDrivingFaults: true,
  seriousFaults: [ 'Signals - Necessary' ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Junctions - Observation' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Dr Fox Farrell',
  address_line_1: 'Dr Fox Farrell',
  address_line_2: '55 Pierrepont Street',
  address_line_3: 'Clifford Place',
  address_line_4: 'Provost Street',
  address_line_5: 'Bascom',
  address_line_6: 'Address Line 5',
  postcode: 'BR82 0DE',
};

export const personlisationCatADI2Pass: PersonalisationDetails = {
  applicationReference: 22123400011,
  category: TestCategory.ADI2,
  date: '13 December 2023',
  location: 'Example Test Centre',
  drivingFaults: [ 'Control - Accelerator, 4', 'Vehicle checks, 3' ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'miss Anna Firstlis',
  address_line_1: 'miss Anna Firstlis',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: 'Address Line 3',
  address_line_5: 'Address Line 4',
  address_line_6: 'Address Line 5',
  postcode: 'PO57 0DE',
};

export const personlisationCatADI2Fail: PersonalisationDetails = {
  applicationReference: 22123903031,
  category: TestCategory.ADI2,
  date: '27 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [
    'Vehicle checks, 2',
    'Pedestrian crossings, 1',
    'Use of mirrors - Signalling, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Signals - Correctly' ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Use of mirrors - Change direction' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Mr Polo Shirt',
  address_line_1: 'Mr Polo Shirt',
  address_line_2: '4567 Station Street',
  address_line_3: 'Someplace',
  address_line_4: 'Sometown',
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'AB12 3CD',
};

export const personlisationPADI: PersonalisationDetails = {
  applicationReference: 23123427011,
  category: TestCategory.ADI3,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'Ssdfghdfgdfgd' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'Review feedback',
  positionType: 'in',
  prn: '1105322',
  candidateName: 'Mr Will Byers',
  address_line_1: 'Mr Will Byers',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personlisationCatCPCPass: PersonalisationDetails = {
  applicationReference: 22123466011,
  category: TestCategory.CCPC,
  date: '13 December 2023',
  location: 'Example Test Centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  q1Score: '5',
  q2Score: '5',
  q3Score: '5',
  q4Score: '5',
  q5Score: '20',
  totalScore: '40',
  showLGVText: true,
  showPCVText: false,
  candidateName: 'Miss Jennifer Aniston',
  address_line_1: 'Miss Jennifer Aniston',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: 'Address Line 3',
  address_line_5: 'Address Line 4',
  address_line_6: 'Address Line 5',
  postcode: 'PO57 0DE',
};

export const personlisationCatCPCFail: PersonalisationDetails = {
  applicationReference: 22123470019,
  category: TestCategory.CCPC,
  date: '28 November 2023',
  location: 'Example Test Centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  q1Score: '10',
  q2Score: '5',
  q3Score: '5',
  q4Score: '5',
  q5Score: '5',
  totalScore: '30',
  showLGVText: true,
  showPCVText: false,
  candidateName: 'Mrs Ken Doe',
  address_line_1: 'Mrs Ken Doe',
  address_line_2: 'My House',
  address_line_3: 'Someplace',
  address_line_4: 'Sometown',
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'AB45 6CD',
};

export const personlisationCatHomePass: PersonalisationDetails = {
  applicationReference: 22123412022,
  category: TestCategory.F,
  date: '28 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [
    'Signals - Necessary, 1',
    'Junctions - Turning right, 1',
    'Vehicle checks, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: true,
  showProvLicenceRetainedByDriver: false,
  candidateName: 'Miss Anna Shaw',
  address_line_1: 'Miss Anna Shaw',
  address_line_2: '999 Letsby Avenue',
  address_line_3: 'Someplace',
  address_line_4: 'Sometown',
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'AB67 8CD',
};

export const personlisationCatHomeFail: PersonalisationDetails = {
  applicationReference: 22123499031,
  category: TestCategory.G,
  date: '28 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [
    'Control - Gears, 1',
    'Pedestrian crossings, 1',
    'Reverse - Control, 1',
    'Vehicle checks, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Use of mirrors - Change direction' ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Signals - Timed' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Mr Buxton Phil',
  address_line_1: 'Mr Buxton Phil',
  address_line_2: '3456 Station Street',
  address_line_3: 'Someplace',
  address_line_4: 'Sometown',
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'AB12 3CD',
};

export const personlisationCatAM1Pass: PersonalisationDetails = {
  applicationReference: 10123400011,
  category: TestCategory.EUA1M1,
  date: '14 December 2023',
  location: 'Example Test Centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  showEmergencyStop: true,
  showEmergencyFirstAttempt: true,
  emergencyFirstAttempt: '50 km/h',
  showEmergencySecondAttempt: true,
  emergencySecondAttempt: '50 km/h',
  showAvoidanceExercise: true,
  showAvoidanceFirstAttempt: true,
  avoidanceFirstAttempt: '50 km/h',
  showAvoidanceSecondAttempt: true,
  avoidanceSecondAttempt: '50 km/h',
  candidateName: 'Ms Alisa Garza',
  address_line_1: 'Ms Alisa Garza',
  address_line_2: '33 Montgomery Street',
  address_line_3: 'Coventry Road',
  address_line_4: 'Fuller Place',
  address_line_5: 'Salix',
  address_line_6: 'Address Line 5',
  postcode: 'BR82 0DE',
};

export const personlisationCatAM1Fail: PersonalisationDetails = {
  applicationReference: 10123422011,
  category: TestCategory.EUA1M1,
  date: '29 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [ 'Move away - Safety, 1' ],
  showDrivingFaults: true,
  seriousFaults: [
    'Slalom / Figure 8',
    'Avoidance Ex. Control Stop - Speed requirement not met',
  ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Move away - Control' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  showEmergencyStop: true,
  showEmergencyFirstAttempt: true,
  emergencyFirstAttempt: '33 km/h',
  showEmergencySecondAttempt: true,
  emergencySecondAttempt: '6 km/h',
  showAvoidanceExercise: true,
  showAvoidanceFirstAttempt: true,
  avoidanceFirstAttempt: '33 km/h',
  showAvoidanceSecondAttempt: true,
  avoidanceSecondAttempt: '55 km/h',
  candidateName: 'Ms Shirley Benton',
  address_line_1: 'Ms Shirley Benton',
  address_line_2: '57 Furman Street',
  address_line_3: 'Rapelye Street',
  address_line_4: 'Halsey Street',
  address_line_5: 'Dale',
  address_line_6: 'Address Line 5',
  postcode: 'BR82 0DE',
};

export const personlisationCatAM2Pass: PersonalisationDetails = {
  applicationReference: 10123433011,
  category: TestCategory.EUAMM2,
  date: '14 December 2023',
  location: 'Example Test Centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: [ 'Control - Clutch' ],
  showDangerousFaults: true,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Dr Fox Farrell',
  address_line_1: 'Dr Fox Farrell',
  address_line_2: '55 Pierrepont Street',
  address_line_3: 'Clifford Place',
  address_line_4: 'Provost Street',
  address_line_5: 'Bascom',
  address_line_6: 'Address Line 5',
  postcode: 'BR82 0DE',
};

export const personlisationCatAM2Fail: PersonalisationDetails = {
  applicationReference: 10123444011,
  category: TestCategory.EUA1M2,
  date: '29 November 2023',
  location: 'Example Test Centre',
  drivingFaults: [
    'Response to signs / signals - Traffic controllers, 2',
    'Use of speed, 1',
    'Response to signs / signals - Other road users, 1',
    'Safety and balance questions, 1',
  ],
  showDrivingFaults: true,
  seriousFaults: [ 'Rear Observation - Change Direction' ],
  showSeriousFaults: true,
  dangerousFaults: [ 'Response to signs / signals - Traffic signs' ],
  showDangerousFaults: true,
  showEcoText: true,
  showEtaText: true,
  showEtaVerbal: true,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  candidateName: 'Miss Sheila Kirk',
  address_line_1: 'Miss Sheila Kirk',
  address_line_2: '33',
  address_line_3: 'Albemarle Road',
  address_line_4: 'Joralemon Street',
  address_line_5: 'Malo',
  address_line_6: 'Address Line 5',
  postcode: 'BR82 0DE',
};

export const personlisationCatADI3Pass: PersonalisationDetails = {
  applicationReference: 23123428013,
  category: TestCategory.ADI3,
  date: '14 December 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '0',
  lp1Score: '0',
  lp2Score: '0',
  lp3Score: '0',
  lp4Score: '0',
  riskManagementScore: '15',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '3',
  teachingLearningStrategiesScore: '15',
  tls1Score: '0',
  tls2Score: '0',
  tls3Score: '0',
  tls4Score: '3',
  tls5Score: '3',
  tls6Score: '3',
  tls7Score: '3',
  tls8Score: '3',
  totalScore: '30',
  studentLevel: 'Trained',
  lessonThemes: [ 'Junctions', 'Motorways' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'M',
  positionType: 'in',
  prn: '4405399',
  candidateName: 'Mr Mike Wheeler',
  address_line_1: 'Mr Mike Wheeler',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personlisationCatADI3Fail: PersonalisationDetails = {
  applicationReference: 23123427011,
  category: TestCategory.ADI3,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: true,
  isSC: false,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'ADI Part 3',
  lessonPlanningScore: '4',
  lp1Score: '1',
  lp2Score: '1',
  lp3Score: '1',
  lp4Score: '1',
  riskManagementScore: '13',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '1',
  teachingLearningStrategiesScore: '4',
  tls1Score: '0',
  tls2Score: '1',
  tls3Score: '0',
  tls4Score: '0',
  tls5Score: '0',
  tls6Score: '1',
  tls7Score: '1',
  tls8Score: '1',
  totalScore: '21',
  studentLevel: 'FLH Experienced',
  lessonThemes: [ 'Defensive driving', 'Ssdfghdfgdfgd' ],
  grade: '',
  showGrade: false,
  result: 'were unsuccessful',
  feedback: 'Review feedback',
  positionType: 'in',
  prn: '1105322',
  candidateName: 'Mr Will Byers',
  address_line_1: 'Mr Will Byers',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};

export const personlisationCatSCPass: PersonalisationDetails = {
  applicationReference: 23150009011,
  category: TestCategory.SC,
  date: '30 November 2023',
  location: 'Isolated test centre',
  drivingFaults: '',
  showDrivingFaults: false,
  seriousFaults: '',
  showSeriousFaults: false,
  dangerousFaults: '',
  showDangerousFaults: false,
  showEcoText: false,
  showEtaText: false,
  showEtaVerbal: false,
  showEtaPhysical: false,
  showProvLicenceRetainedByDvsa: false,
  showProvLicenceRetainedByDriver: true,
  isADI3: false,
  isSC: true,
  RMFail: false,
  code4: false,
  categoryDescriptor: 'Standards Check',
  lessonPlanningScore: '10',
  lp1Score: '3',
  lp2Score: '2',
  lp3Score: '3',
  lp4Score: '2',
  riskManagementScore: '15',
  rm1Score: '3',
  rm2Score: '3',
  rm3Score: '3',
  rm4Score: '3',
  rm5Score: '3',
  teachingLearningStrategiesScore: '22',
  tls1Score: '3',
  tls2Score: '3',
  tls3Score: '3',
  tls4Score: '3',
  tls5Score: '2',
  tls6Score: '3',
  tls7Score: '3',
  tls8Score: '2',
  totalScore: '47',
  studentLevel: 'Trained',
  lessonThemes: [ 'Town & City driving' ],
  grade: 'A',
  showGrade: true,
  result: 'passed',
  feedback: 'Saul goodman',
  positionType: 'on',
  prn: '3322408',
  candidateName: 'Mr Stan Lee',
  address_line_1: 'Mr Stan Lee',
  address_line_2: 'Address Line 1',
  address_line_3: 'Address Line 2',
  address_line_4: undefined,
  address_line_5: undefined,
  address_line_6: undefined,
  postcode: 'PO57 0DE',
};
